# Supported Funding Model Platforms
funding_platforms = {
    "GitHub": {"type": "sponsors", "users": []},
    "Patreon": {"type": "patreon", "users": []},
    "OpenCollective": {"type": "open_collective", "users": []},
    "Ko-fi": {"type": "ko_fi", "users": []},
    "Tidelift": {"type": "tidelift", "package": ""},
    "Community Bridge": {"type": "community_bridge", "project": ""},
    "Liberapay": {"type": "liberapay", "users": []},
    "IssueHunt": {"type": "issuehunt", "users": []},
    "Otechie": {"type": "otechie", "users": []},
    "Custom": {"type": "custom", "urls": []},
}

# Configuring the supported funding platforms
funding_platforms["GitHub"]["users"] = ["user1", "user2"]
funding_platforms["Patreon"]["users"] = ["patreon_user"]
funding_platforms["OpenCollective"]["users"] = ["open_collective_user"]
funding_platforms["Ko-fi"]["users"] = ["ko_fi_user"]
funding_platforms["Tidelift"]["package"] = "npm/babel"
funding_platforms["Community Bridge"]["project"] = "cloud-foundry"
funding_platforms["Liberapay"]["users"] = ["liberapay_user"]
funding_platforms["IssueHunt"]["users"] = ["issuehunt_user"]
funding_platforms["Otechie"]["users"] = ["otechie_user"]
funding_platforms["Custom"]["urls"] = ["https://buymeacoffee.com/jameshenry"]
